"use client";
/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Praxis chat surface — PROOF (standalone, no auth, mock data).
 * Step-2 interactions: ⌘K palette, slash-commands, @mention routing,
 * reactions, AND an artifacts side-panel (employees hand you real
 * deliverables you can read / copy / download while you keep chatting).
 *   →  /rebrand-preview/chat
 */

import * as React from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles, Code2, TrendingUp, Megaphone, DollarSign, Wrench, ShieldCheck,
  Users, Scale, SquarePen, Menu, ArrowUp, Paperclip, Mic, Search, Settings,
  MoreHorizontal, Copy, RefreshCw, Command, AtSign, Slash, CornerDownLeft,
  Hammer, FileText, Zap, X, Download, Printer, Check, AudioLines, PhoneOff, MicOff, Keyboard,
} from "lucide-react";
import { Button } from "@/components/ui/button";

type Icon = React.ComponentType<{ className?: string }>;
type EmpId = "atlas" | "engineering" | "sales" | "marketing" | "finance" | "ops" | "compliance" | "hr" | "legal";

const EMP: Record<EmpId, { name: string; role: string; icon: Icon }> = {
  atlas: { name: "Atlas", role: "Chief of Staff", icon: Sparkles },
  engineering: { name: "Engineering", role: "Build & Ship", icon: Code2 },
  sales: { name: "Sales", role: "Pipeline & Close", icon: TrendingUp },
  marketing: { name: "Marketing", role: "Brand & Demand", icon: Megaphone },
  finance: { name: "Finance", role: "Books & Forecast", icon: DollarSign },
  ops: { name: "Operations", role: "Systems & Process", icon: Wrench },
  compliance: { name: "Compliance", role: "Risk & Controls", icon: ShieldCheck },
  hr: { name: "HR", role: "People & Culture", icon: Users },
  legal: { name: "Legal", role: "Counsel & Contracts", icon: Scale },
};
const ORDER: EmpId[] = ["atlas", "engineering", "sales", "marketing", "finance", "ops", "compliance", "hr", "legal"];

type Artifact = { id: string; title: string; type: string; by: EmpId; content: string };
type Msg = { id: string; role: "user" | "assistant"; emp?: EmpId; content: string; stream?: boolean; artifact?: Artifact };

const ART_MIGRATION: Artifact = {
  id: "art-rls", title: "RLS migration — account-scoped batch", type: "migration", by: "engineering",
  content: `-- Praxis · enable RLS + owner policies on 38 account-scoped tables
-- Generated by Engineering · review before applying

do $$
declare t text;
begin
  foreach t in array array[
    'conduit_messages','conduit_conversations','conduit_artifacts',
    'conduit_memory','conduit_builds' /* …33 more */
  ] loop
    execute format('alter table public.%I enable row level security;', t);
    execute format($p$
      create policy owner_all on public.%I
      using (account_id = (select id from conduit_accounts
                           where owner_user_id = auth.uid()))
      with check (account_id = (select id from conduit_accounts
                                where owner_user_id = auth.uid()));
    $p$, t);
  end loop;
end $$;

-- Then: move conduit_secrets → Vault, re-run get_advisors.
-- Definition of done: 0 rls_disabled_in_public ERRORs.`,
};
const ART_POST: Artifact = {
  id: "art-post", title: "Launch Day 1 — origin story", type: "post", by: "marketing",
  content: `Six weeks ago my AI workforce died. No heartbeat, no warning — it just stopped, and I didn't notice for days.

So I rebuilt it the right way. Praxis is a team of AI employees that actually run the shop: engineering ships, marketing drafts, finance forecasts — and a watchdog texts me the second anything breaks.

Today it goes live.

If you've ever wished you had a team but it was just you — this is for you. Link in bio. 🔥`,
};

const CONVOS: { id: string; title: string; emp: EmpId; time: string }[] = [
  { id: "c1", title: "RLS policies before launch", emp: "engineering", time: "now" },
  { id: "c2", title: "Launch week content plan", emp: "marketing", time: "2h" },
  { id: "c3", title: "Q3 runway model", emp: "finance", time: "Yest" },
  { id: "c4", title: "Weekly cross-org status", emp: "atlas", time: "Mon" },
];
const THREADS: Record<string, Msg[]> = {
  c1: [
    { id: "m1", role: "user", content: "Where are we on locking down the database before we let real users in?" },
    { id: "m2", role: "assistant", emp: "engineering", content: "We have 50 tables with RLS disabled — that's the blocker. 38 are account-scoped, 8 public-read, 4 need custom policies. I drafted the account-scoped batch — open it on the right.", artifact: ART_MIGRATION },
  ],
  c2: [{ id: "m1", role: "user", content: "Give me a content plan for launch week." }, { id: "m2", role: "assistant", emp: "marketing", content: "Founder-led, 5 days. Here's Day 1 drafted in your voice — open it on the right.", artifact: ART_POST }],
  c3: [{ id: "m1", role: "user", content: "What's our runway at current burn?" }, { id: "m2", role: "assistant", emp: "finance", content: "Inside the $5/day cap plus infra — ~$190/mo. Runway isn't the constraint; focus is. Hold spend flat until the first cohort." }],
  c4: [{ id: "m1", role: "user", content: "Weekly cross-org status." }, { id: "m2", role: "assistant", emp: "atlas", content: "Engineering: RLS underway. Marketing: plan drafted. Finance: flat. Legal: ToS ready. Blocking on you: confirm 4 RLS rules + record two videos." }],
};
const GREETING: Record<EmpId, string> = {
  atlas: "Atlas here. I hold the whole org's context — tell me what to move and I'll route it.",
  engineering: "Engineering. What are we building, shipping, or fixing?",
  sales: "Sales. Point me at the pipeline — who do we move and by when?",
  marketing: "Marketing. Want copy, a campaign, or an asset? I'll make it on-brand.",
  finance: "Finance. Ask me about cash, runway, or a forecast — numbers first.",
  ops: "Operations. Name the bottleneck and I'll wire the fix.",
  compliance: "Compliance. I'll check anything against the rule and flag real risk.",
  hr: "HR. Hiring, onboarding, or team stuff — I'll keep it human.",
  legal: "Legal. Bottom line first, then the reasoning. What are we reviewing?",
};
const SUGGEST: Record<EmpId, string[]> = {
  atlas: ["What's blocking me today?", "Summarize the week", "Pull in Engineering"],
  engineering: ["Build me the RLS migration", "Deploy to preview", "What needs a Max session?"],
  sales: ["Who's gone cold?", "Draft a follow-up", "Pipeline by stage"],
  marketing: ["Draft today's launch post", "3 hook ideas", "Plan the launch"],
  finance: ["Show runway", "Biggest cost driver", "Model +2 hires"],
  ops: ["What's flaky?", "Map the workflow", "Vendor list"],
  compliance: ["Pre-launch risk check", "Privacy gaps", "What needs a policy?"],
  hr: ["Draft a role", "Onboarding checklist", "Team pulse"],
  legal: ["Review the ToS", "Safe to sign?", "IP exposure"],
};
const REPLY: Record<EmpId, string> = {
  atlas: "Got it. I'll coordinate that across the team and surface anything that needs your call.",
  engineering: "Done — I've drafted it. Open the artifact on the right to review, then I'll apply it.",
  sales: "On it — I'll move that through the pipeline and come back with the next action and a date.",
  marketing: "Love it. I drafted it in your voice — open the artifact on the right.",
  finance: "Noted. I'll model it and give you the number plus the implication.",
  ops: "I see the bottleneck. I'll wire the fix and confirm it's running.",
  compliance: "I'll check it against the rule and flag risk precisely.",
  hr: "Understood. I'll handle it candidly and keep it human.",
  legal: "Bottom line first: safe-to-sign or fix-before-signing, with the why.",
};
const SLASH: { cmd: string; desc: string; emp: EmpId; template: string; icon: Icon }[] = [
  { cmd: "/build", desc: "Build something with Engineering", emp: "engineering", template: "Build me ", icon: Hammer },
  { cmd: "/draft", desc: "Draft copy with Marketing", emp: "marketing", template: "Draft me ", icon: FileText },
  { cmd: "/plan", desc: "Plan with Atlas", emp: "atlas", template: "Plan ", icon: Sparkles },
  { cmd: "/numbers", desc: "Run numbers with Finance", emp: "finance", template: "Run the numbers on ", icon: DollarSign },
  { cmd: "/review", desc: "Legal review", emp: "legal", template: "Review ", icon: Scale },
];

// Deliverables are type-aware: code/migrations download as runnable source;
// documents download as Markdown and can also export to PDF.
const DOC_TYPES = new Set(["post", "doc", "brief", "contract", "proposal", "report", "letter", "plan"]);
function extFor(type: string) { return type === "migration" ? "sql" : type === "code" ? "ts" : "md"; }
function slugify(s: string) { return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function escapeHtml(s: string) { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }

function StreamingText({ text, animate }: { text: string; animate: boolean }) {
  const words = React.useMemo(() => text.split(" "), [text]);
  const [n, setN] = React.useState(animate ? 0 : words.length);
  React.useEffect(() => {
    if (!animate) { setN(words.length); return; }
    let i = 0; const id = setInterval(() => { i += 1; setN(i); if (i >= words.length) clearInterval(id); }, 26);
    return () => clearInterval(id);
  }, [animate, words.length]);
  return <span>{words.slice(0, n).join(" ")}{animate && n < words.length && <span className="ml-0.5 inline-block h-4 w-[3px] translate-y-0.5 animate-pulse rounded-full bg-primary align-middle" />}</span>;
}

export default function ChatPreview() {
  const [activeConvo, setActiveConvo] = React.useState("c1");
  const [activeEmp, setActiveEmp] = React.useState<EmpId>("engineering");
  const [messages, setMessages] = React.useState<Msg[]>(THREADS.c1);
  const [input, setInput] = React.useState("");
  const [drawer, setDrawer] = React.useState(false);
  const [thinking, setThinking] = React.useState(false);
  const [copied, setCopied] = React.useState<string | null>(null);
  const [reactions, setReactions] = React.useState<Record<string, string>>({});
  const [palette, setPalette] = React.useState(false);
  const [paletteQ, setPaletteQ] = React.useState("");
  const [artifact, setArtifact] = React.useState<Artifact | null>(null);
  const [artCopied, setArtCopied] = React.useState(false);
  const [recording, setRecording] = React.useState(false);
  const [recSecs, setRecSecs] = React.useState(0);
  const [liveRoom, setLiveRoom] = React.useState(false);
  const [liveStatus, setLiveStatus] = React.useState<"listening" | "speaking">("listening");
  const [muted, setMuted] = React.useState(false);
  const [caption, setCaption] = React.useState("");
  const scrollRef = React.useRef<HTMLDivElement>(null);
  const taRef = React.useRef<HTMLTextAreaElement>(null);
  const emp = EMP[activeEmp];

  const slashMatch = input.startsWith("/") && !input.includes(" ");
  const mentionMatch = input.match(/(^|\s)@(\w*)$/);
  const menu: "slash" | "mention" | null = slashMatch ? "slash" : mentionMatch ? "mention" : null;
  const slashItems = SLASH.filter((s) => s.cmd.startsWith(input.toLowerCase()));
  const mentionItems = ORDER.filter((id) => EMP[id].name.toLowerCase().startsWith((mentionMatch?.[2] ?? "").toLowerCase()));

  React.useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setPalette((p) => !p); }
      if (e.key === "Escape") { setPalette(false); setArtifact(null); }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);
  React.useEffect(() => {
    const t = setTimeout(() => scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }), 60);
    return () => clearTimeout(t);
  }, [messages, thinking]);

  function openConvo(id: string) { const c = CONVOS.find((x) => x.id === id); if (!c) return; setActiveConvo(id); setActiveEmp(c.emp); setMessages(THREADS[id] ?? []); setDrawer(false); }
  function switchEmp(id: EmpId) { setActiveEmp(id); setActiveConvo(""); setMessages([{ id: "g" + Date.now(), role: "assistant", emp: id, content: GREETING[id], stream: true }]); setPalette(false); }
  function grow() { const ta = taRef.current; if (!ta) return; ta.style.height = "auto"; ta.style.height = Math.min(ta.scrollHeight, 160) + "px"; }
  function push(text: string) {
    if (!text.trim() || thinking) return;
    const t = text.toLowerCase();
    let art: Artifact | undefined;
    if (/build|rls|migration|brief|deploy|schema|policy/.test(t)) art = ART_MIGRATION;
    else if (/draft|post|write|copy|launch|campaign|content/.test(t)) art = ART_POST;
    setMessages((m) => [...m, { id: "u" + Date.now(), role: "user", content: text.trim() }]);
    setInput(""); if (taRef.current) taRef.current.style.height = "auto";
    setThinking(true);
    setTimeout(() => {
      setMessages((m) => [...m, { id: "a" + Date.now(), role: "assistant", emp: activeEmp, content: REPLY[activeEmp], stream: true, artifact: art ? { ...art, by: activeEmp } : undefined }]);
      setThinking(false);
    }, 950);
  }
  function copy(m: Msg) { navigator.clipboard?.writeText(m.content).catch(() => {}); setCopied(m.id); setTimeout(() => setCopied((c) => (c === m.id ? null : c)), 1400); }
  function react(id: string, e: string) { setReactions((r) => ({ ...r, [id]: r[id] === e ? "" : e })); }
  React.useEffect(() => {
    if (!recording) return;
    setRecSecs(0);
    const id = setInterval(() => setRecSecs((s) => s + 1), 1000);
    return () => clearInterval(id);
  }, [recording]);
  function finishRec() { setRecording(false); setInput((v) => (v ? v + " " : "") + "How long until the RLS migration is safe to ship?"); setTimeout(() => { taRef.current?.focus(); grow(); }, 0); }
  function cancelRec() { setRecording(false); }
  React.useEffect(() => {
    if (!liveRoom) return;
    const lines = [GREETING[activeEmp], REPLY[activeEmp], "Want me to start on that right now?"];
    let i = 0; let alive = true;
    const cycle = () => {
      if (!alive) return;
      setLiveStatus("listening"); setCaption("");
      setTimeout(() => { if (alive) { setLiveStatus("speaking"); setCaption(lines[i % lines.length]); i += 1; } }, 1800);
      setTimeout(() => { if (alive) cycle(); }, 5200);
    };
    cycle();
    return () => { alive = false; };
  }, [liveRoom, activeEmp]);
  function endCall() {
    setLiveRoom(false);
    setMessages((m) => [...m, { id: "vc" + Date.now(), role: "assistant", emp: activeEmp, content: `🎙️ Voice room ended — ${REPLY[activeEmp]}` }]);
  }
  function applySlash(s: typeof SLASH[number]) { setActiveEmp(s.emp); setInput(s.template); taRef.current?.focus(); }
  function applyMention(id: EmpId) { setInput((v) => v.replace(/(^|\s)@\w*$/, (_m, p1) => `${p1}@${EMP[id].name} `)); setActiveEmp(id); taRef.current?.focus(); }
  function copyArtifact() { if (!artifact) return; navigator.clipboard?.writeText(artifact.content).catch(() => {}); setArtCopied(true); setTimeout(() => setArtCopied(false), 1400); }
  function downloadArtifact() {
    if (!artifact) return;
    const blob = new Blob([artifact.content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${slugify(artifact.title)}.${extFor(artifact.type)}`; a.click();
    URL.revokeObjectURL(url);
  }
  function downloadPdf() {
    if (!artifact) return;
    const w = window.open("", "_blank"); if (!w) return;
    w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(artifact.title)}</title><style>body{font-family:Georgia,'Times New Roman',serif;max-width:680px;margin:48px auto;padding:0 24px;color:#111;line-height:1.6}.k{color:#888;text-transform:uppercase;letter-spacing:.14em;font-size:11px;font-family:system-ui,sans-serif}h1{font-family:system-ui,sans-serif;font-size:22px;margin:.2em 0 1em}pre{white-space:pre-wrap;font-family:inherit;margin:0}</style></head><body><div class="k">${escapeHtml(artifact.type)} · by ${escapeHtml(EMP[artifact.by].name)} · Praxis</div><h1>${escapeHtml(artifact.title)}</h1><pre>${escapeHtml(artifact.content)}</pre></body></html>`);
    w.document.close(); w.focus(); setTimeout(() => { try { w.print(); } catch { /* ignore */ } }, 350);
  }

  const last = messages[messages.length - 1];
  const showSuggest = !thinking && last?.role === "assistant" && menu === null;

  const Rail = (
    <div className="flex h-full flex-col">
      <div className="flex items-center justify-between gap-2 p-3">
        <div className="flex items-center gap-2 px-1"><div className="grid size-8 place-items-center rounded-lg bg-primary"><span className="font-mono text-sm font-bold text-primary-foreground">P</span></div><span className="font-semibold tracking-tight">Praxis</span></div>
        <Button size="icon" variant="secondary" className="size-9 rounded-lg bg-secondary hover:bg-input" onClick={() => switchEmp("atlas")}><SquarePen className="size-4" /></Button>
      </div>
      <div className="px-3 pb-2">
        <button onClick={() => setPalette(true)} className="flex h-9 w-full items-center gap-2 rounded-lg border border-input bg-secondary/50 px-3 text-sm text-muted-foreground hover:bg-secondary"><Search className="size-4" /> Search<span className="ml-auto flex items-center gap-0.5 rounded border border-white/10 px-1.5 py-0.5 text-[10px] font-mono"><Command className="size-2.5" />K</span></button>
      </div>
      <div className="min-h-0 flex-1 overflow-y-auto px-2 pb-2">
        <p className="wm-label px-2 py-2">Recent</p>
        {CONVOS.map((c) => { const E = EMP[c.emp]; const on = c.id === activeConvo; return (
          <button key={c.id} onClick={() => openConvo(c.id)} className={`mb-1 flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left transition-colors ${on ? "bg-secondary" : "hover:bg-secondary/60"}`}>
            <span className={`grid size-8 shrink-0 place-items-center rounded-lg bg-card text-primary ${on ? "ring-1 ring-primary/40" : ""}`}><E.icon className="size-4" /></span>
            <span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{c.title}</span><span className="block truncate text-xs text-muted-foreground">{E.name} · {c.time}</span></span>
          </button>
        ); })}
      </div>
      <div className="flex items-center gap-3 border-t border-white/8 p-3"><span className="grid size-8 place-items-center rounded-full bg-secondary text-sm font-semibold">L</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">Luis Garcia</span><span className="block truncate text-xs text-muted-foreground">Founder · Pro</span></span><Settings className="size-4 text-muted-foreground" /></div>
    </div>
  );

  return (
    <div className="wm-rebrand flex h-[100dvh] w-full overflow-hidden text-foreground">
      <aside className="hidden w-72 shrink-0 border-r border-white/8 bg-card/40 backdrop-blur-xl lg:block">{Rail}</aside>

      <AnimatePresence>
        {drawer && (<>
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setDrawer(false)} className="fixed inset-0 z-40 bg-black/60 lg:hidden" />
          <motion.aside initial={{ x: "-100%" }} animate={{ x: 0 }} exit={{ x: "-100%" }} transition={{ type: "spring", stiffness: 320, damping: 34 }} className="fixed inset-y-0 left-0 z-50 w-[82%] max-w-xs border-r border-white/8 bg-card lg:hidden">{Rail}</motion.aside>
        </>)}
      </AnimatePresence>

      {/* ⌘K palette */}
      <AnimatePresence>
        {palette && (
          <div className="fixed inset-0 z-[60] flex items-start justify-center p-4 pt-[12vh]">
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setPalette(false)} className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
            <motion.div initial={{ opacity: 0, y: -12, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: -8, scale: 0.98 }} transition={{ type: "spring", stiffness: 300, damping: 26 }} className="relative w-full max-w-lg overflow-hidden rounded-2xl border border-white/10 bg-card wm-glow">
              <div className="flex items-center gap-2 border-b border-white/8 px-4"><Search className="size-4 text-muted-foreground" /><input autoFocus value={paletteQ} onChange={(e) => setPaletteQ(e.target.value)} placeholder="Jump to a teammate, start a chat…" className="h-12 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" /><kbd className="rounded border border-white/10 px-1.5 py-0.5 text-[10px] text-muted-foreground">esc</kbd></div>
              <div className="max-h-72 overflow-y-auto p-2">
                <p className="wm-label px-2 py-1.5">Actions</p>
                <button onClick={() => switchEmp("atlas")} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left text-sm hover:bg-secondary"><span className="grid size-7 place-items-center rounded-md bg-secondary text-primary"><SquarePen className="size-4" /></span>New chat</button>
                <p className="wm-label px-2 py-1.5 pt-3">Talk to</p>
                {ORDER.filter((id) => EMP[id].name.toLowerCase().includes(paletteQ.toLowerCase())).map((id) => { const E = EMP[id]; return <button key={id} onClick={() => switchEmp(id)} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left text-sm hover:bg-secondary"><span className="grid size-7 place-items-center rounded-md bg-secondary text-primary"><E.icon className="size-4" /></span><span className="flex-1">{E.name}</span><span className="text-xs text-muted-foreground">{E.role}</span></button>; })}
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* artifact side-panel */}
      <AnimatePresence>
        {artifact && (
          <div className="fixed inset-0 z-50 flex">
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setArtifact(null)} className="flex-1 bg-black/50" />
            <motion.div initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", stiffness: 300, damping: 32 }} className="flex h-full w-full max-w-2xl flex-col border-l border-white/10 bg-card">
              <div className="flex items-center gap-3 border-b border-white/8 px-5 py-4">
                <span className="grid size-9 place-items-center rounded-xl bg-secondary text-primary"><FileText className="size-5" /></span>
                <div className="min-w-0 flex-1"><p className="wm-label">{artifact.type} · by {EMP[artifact.by].name}</p><h2 className="truncate text-lg font-semibold">{artifact.title}</h2></div>
                <Button onClick={copyArtifact} size="icon" variant="ghost" className="size-9 rounded-lg text-muted-foreground hover:bg-secondary" title="Copy">{artCopied ? <span className="text-xs text-primary">✓</span> : <Copy className="size-4" />}</Button>
                <Button onClick={downloadArtifact} size="sm" variant="secondary" className="gap-1.5 rounded-lg bg-secondary text-xs" title={`Download .${extFor(artifact.type)}`}><Download className="size-3.5" /> {extFor(artifact.type).toUpperCase()}</Button>
                {DOC_TYPES.has(artifact.type) && <Button onClick={downloadPdf} size="sm" variant="secondary" className="gap-1.5 rounded-lg bg-secondary text-xs" title="Save as PDF"><Printer className="size-3.5" /> PDF</Button>}
                <Button onClick={() => setArtifact(null)} size="icon" variant="ghost" className="size-9 rounded-lg text-muted-foreground hover:bg-secondary"><X className="size-4" /></Button>
              </div>
              <div className="min-h-0 flex-1 overflow-y-auto p-5">
                <pre className="whitespace-pre-wrap font-mono text-[13px] leading-relaxed text-foreground/90">{artifact.content}</pre>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* in-chat live voice room — full-screen, returns to the same thread */}
      <AnimatePresence>
        {liveRoom && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="wm-aurora fixed inset-0 z-[70] flex flex-col items-center justify-between bg-background px-6 py-12 text-center">
            <div className="flex flex-col items-center gap-1.5">
              <p className="wm-label flex items-center gap-1.5"><span className="size-1.5 animate-pulse rounded-full bg-primary" /> Live room</p>
              <h2 className="text-2xl font-semibold tracking-tight">{emp.name}</h2>
              <p className="text-sm text-muted-foreground">{muted ? "You're muted" : liveStatus === "speaking" ? `${emp.name} is speaking…` : "Listening…"}</p>
            </div>
            <div className="relative grid place-items-center">
              {[0, 1, 2].map((r) => (<motion.span key={r} className="absolute size-44 rounded-full border border-primary/30" animate={{ scale: [1, 1.9], opacity: [0.5, 0] }} transition={{ duration: 2.4, repeat: Infinity, delay: r * 0.8, ease: "easeOut" }} />))}
              <motion.div className="grid size-44 place-items-center rounded-full wm-glow" style={{ background: "radial-gradient(circle at 50% 32%, var(--wm-ember-hi), var(--wm-ember-deep))" }} animate={liveStatus === "speaking" ? { scale: [1, 1.08, 0.98, 1.05, 1] } : { scale: [1, 1.03, 1] }} transition={{ duration: liveStatus === "speaking" ? 0.6 : 2, repeat: Infinity, ease: "easeInOut" }}>
                <emp.icon className="size-16 text-primary-foreground" />
              </motion.div>
            </div>
            <div className="flex min-h-16 max-w-md items-center text-lg leading-relaxed">{caption}</div>
            <div className="flex items-center gap-5">
              <button onClick={() => setMuted((m) => !m)} className={`grid size-14 place-items-center rounded-full border border-white/10 ${muted ? "bg-secondary text-primary" : "bg-secondary/60 text-foreground hover:bg-secondary"}`}>{muted ? <MicOff className="size-6" /> : <Mic className="size-6" />}</button>
              <button onClick={endCall} className="grid size-16 place-items-center rounded-full bg-destructive text-white"><PhoneOff className="size-7" /></button>
              <button onClick={() => setLiveRoom(false)} title="Back to text" className="grid size-14 place-items-center rounded-full border border-white/10 bg-secondary/60 text-foreground hover:bg-secondary"><Keyboard className="size-6" /></button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="flex min-w-0 flex-1 flex-col">
        <header className="flex items-center gap-3 border-b border-white/8 bg-background/70 px-4 py-3 backdrop-blur">
          <Button size="icon" variant="secondary" className="size-9 rounded-lg bg-secondary lg:hidden" onClick={() => setDrawer(true)}><Menu className="size-4" /></Button>
          <span className="grid size-9 place-items-center rounded-xl bg-secondary text-primary"><emp.icon className="size-5" /></span>
          <div className="min-w-0"><p className="truncate font-semibold leading-tight">{emp.name}</p><p className="flex items-center gap-1.5 text-xs text-muted-foreground"><span className="size-1.5 rounded-full bg-primary" /> {emp.role} · 9 online</p></div>
          <div className="ml-auto flex items-center gap-1.5">
            <button onClick={() => setLiveRoom(true)} className="flex items-center gap-1.5 rounded-full bg-primary px-3 py-1.5 text-xs font-semibold text-primary-foreground wm-glow"><AudioLines className="size-3.5" /> Live</button>
            <button onClick={() => setPalette(true)} className="hidden items-center gap-1.5 rounded-lg border border-white/10 px-2.5 py-1.5 text-xs text-muted-foreground hover:bg-secondary hover:text-foreground sm:flex"><Command className="size-3" />K</button>
          </div>
        </header>

        <div className="no-scrollbar flex items-center gap-2 overflow-x-auto border-b border-white/8 px-4 py-2.5">
          <span className="wm-label shrink-0 pr-1">Talk to</span>
          {ORDER.map((id) => { const E = EMP[id]; const on = id === activeEmp; return <button key={id} onClick={() => switchEmp(id)} className={`flex shrink-0 items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium transition-colors ${on ? "border-primary/50 bg-primary/15 text-foreground" : "border-white/8 text-muted-foreground hover:bg-secondary hover:text-foreground"}`}><E.icon className="size-3.5" />{E.name}</button>; })}
        </div>

        <div ref={scrollRef} className="min-h-0 flex-1 overflow-y-auto">
          <div className="mx-auto flex w-full max-w-3xl flex-col gap-6 px-4 py-7">
            {messages.map((m) => (
              <motion.div key={m.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ type: "spring", stiffness: 260, damping: 28 }}>
                {m.role === "user" ? (
                  <div className="flex justify-end"><div className="max-w-[82%] rounded-2xl rounded-br-md bg-secondary px-4 py-2.5 text-[15px] leading-relaxed">{m.content}</div></div>
                ) : (
                  <div className="group flex gap-3">
                    <span className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg bg-secondary text-primary">{React.createElement(EMP[m.emp ?? activeEmp].icon, { className: "size-4" })}</span>
                    <div className="min-w-0 flex-1">
                      <p className="mb-1 text-sm font-semibold">{EMP[m.emp ?? activeEmp].name}</p>
                      <div className="text-[15px] leading-relaxed text-foreground/90"><StreamingText text={m.content} animate={!!m.stream} /></div>
                      {m.artifact && (
                        <button onClick={() => setArtifact(m.artifact!)} className="mt-3 flex w-full max-w-sm items-center gap-3 rounded-xl border border-white/10 bg-secondary/40 p-3 text-left transition-colors hover:border-primary/40 hover:bg-secondary">
                          <span className="grid size-10 shrink-0 place-items-center rounded-lg bg-primary/15 text-primary"><FileText className="size-5" /></span>
                          <span className="min-w-0 flex-1"><span className="wm-label block">{m.artifact.type}</span><span className="block truncate text-sm font-medium">{m.artifact.title}</span></span>
                          <span className="shrink-0 text-xs text-primary">Open →</span>
                        </button>
                      )}
                      <div className="mt-2 flex items-center gap-1 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100">
                        <button onClick={() => copy(m)} className="flex items-center gap-1 rounded-md px-1.5 py-1 text-xs hover:bg-secondary hover:text-foreground">{copied === m.id ? <span className="text-primary">Copied</span> : <Copy className="size-3.5" />}</button>
                        <button className="rounded-md p-1.5 hover:bg-secondary hover:text-foreground"><RefreshCw className="size-3.5" /></button>
                        <span className="mx-1 h-3 w-px bg-white/10" />
                        <button onClick={() => react(m.id, "🔥")} className="rounded-md px-1.5 py-1 text-sm hover:bg-secondary">🔥</button>
                        <button onClick={() => react(m.id, "👍")} className="rounded-md px-1.5 py-1 text-sm hover:bg-secondary">👍</button>
                      </div>
                      {reactions[m.id] && <span className="mt-1 inline-flex items-center gap-1 rounded-full border border-primary/30 bg-primary/10 px-2 py-0.5 text-xs">{reactions[m.id]}</span>}
                    </div>
                  </div>
                )}
              </motion.div>
            ))}
            {thinking && (<div className="flex gap-3"><span className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg bg-secondary text-primary"><emp.icon className="size-4" /></span><div className="flex items-center gap-1 pt-2">{[0, 1, 2].map((i) => (<motion.span key={i} className="size-1.5 rounded-full bg-muted-foreground" animate={{ opacity: [0.3, 1, 0.3], y: [0, -2, 0] }} transition={{ duration: 1, repeat: Infinity, delay: i * 0.18 }} />))}</div></div>)}
            {showSuggest && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-wrap gap-2 pl-11">{SUGGEST[activeEmp].map((s) => <button key={s} onClick={() => push(s)} className="rounded-full border border-white/10 bg-secondary/50 px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:border-primary/40 hover:bg-secondary hover:text-foreground">{s}</button>)}</motion.div>)}
          </div>
        </div>

        <div className="border-t border-white/8 bg-background/70 px-4 pt-3 pb-[max(0.75rem,env(safe-area-inset-bottom))] backdrop-blur">
          <form onSubmit={(e) => { e.preventDefault(); push(input); }} className="relative mx-auto w-full max-w-3xl">
            <AnimatePresence>
              {menu && (
                <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 6 }} className="absolute bottom-full left-0 mb-2 w-72 overflow-hidden rounded-xl border border-white/10 bg-card wm-glow">
                  <p className="wm-label flex items-center gap-1.5 px-3 py-2">{menu === "slash" ? <><Slash className="size-3" /> Commands</> : <><AtSign className="size-3" /> Route to teammate</>}</p>
                  <div className="max-h-60 overflow-y-auto pb-1">
                    {menu === "slash" ? (slashItems.length ? slashItems : SLASH).map((s) => (
                      <button key={s.cmd} type="button" onClick={() => applySlash(s)} className="flex w-full items-center gap-3 px-3 py-2 text-left hover:bg-secondary"><span className="grid size-7 place-items-center rounded-md bg-secondary text-primary"><s.icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="block font-mono text-sm">{s.cmd}</span><span className="block truncate text-xs text-muted-foreground">{s.desc}</span></span></button>
                    )) : mentionItems.map((id) => { const E = EMP[id]; return (
                      <button key={id} type="button" onClick={() => applyMention(id)} className="flex w-full items-center gap-3 px-3 py-2 text-left hover:bg-secondary"><span className="grid size-7 place-items-center rounded-md bg-secondary text-primary"><E.icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm">{E.name}</span><span className="block truncate text-xs text-muted-foreground">{E.role}</span></span></button>
                    ); })}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
            {recording ? (
              <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} className="flex items-center gap-3 rounded-2xl border border-primary/40 bg-secondary p-2 pl-4 wm-glow">
                <span className="flex shrink-0 items-center gap-1.5 font-mono text-sm font-medium text-primary"><span className="size-2 animate-pulse rounded-full bg-primary" />{Math.floor(recSecs / 60)}:{String(recSecs % 60).padStart(2, "0")}</span>
                <div className="flex h-8 flex-1 items-center gap-[3px] overflow-hidden">
                  {Array.from({ length: 36 }).map((_, i) => (
                    <motion.span key={i} className="h-full w-[3px] shrink-0 origin-center rounded-full bg-primary/70" animate={{ scaleY: [0.2, 0.85, 0.4, 0.7, 0.25] }} transition={{ duration: 0.9, repeat: Infinity, delay: i * 0.045, ease: "easeInOut" }} />
                  ))}
                </div>
                <Button type="button" onClick={cancelRec} size="icon" variant="ghost" className="size-9 shrink-0 rounded-xl text-muted-foreground hover:bg-input"><X className="size-4" /></Button>
                <Button type="button" onClick={finishRec} size="icon" className="size-9 shrink-0 rounded-xl wm-glow"><Check className="size-4" /></Button>
              </motion.div>
            ) : (
              <div className="flex items-end gap-2 rounded-2xl border border-white/10 bg-secondary/60 p-2 transition-all focus-within:border-primary/50 focus-within:bg-secondary focus-within:wm-glow">
                <Button type="button" size="icon" variant="ghost" className="size-9 shrink-0 rounded-xl text-muted-foreground hover:bg-input hover:text-foreground"><Paperclip className="size-4" /></Button>
                <textarea ref={taRef} value={input} rows={1} onChange={(e) => { setInput(e.target.value); grow(); }} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey && !menu) { e.preventDefault(); push(input); } }} placeholder={`Message ${emp.name}…  ·  / for commands  ·  @ to route`} className="max-h-40 flex-1 resize-none bg-transparent py-2 text-[15px] leading-relaxed outline-none placeholder:text-muted-foreground" />
                <Button type="button" onClick={() => setRecording(true)} size="icon" variant="ghost" className="size-9 shrink-0 rounded-xl text-muted-foreground hover:bg-input hover:text-foreground"><Mic className="size-4" /></Button>
                <motion.div whileTap={{ scale: 0.9 }}><Button type="submit" size="icon" disabled={!input.trim() || thinking} className="size-9 shrink-0 rounded-xl wm-glow disabled:opacity-40"><ArrowUp className="size-4" /></Button></motion.div>
              </div>
            )}
            <p className="wm-label mt-2 flex items-center justify-center gap-3"><span className="flex items-center gap-1"><Command className="size-3" />K palette</span><span className="flex items-center gap-1"><Slash className="size-3" />commands</span><span className="flex items-center gap-1"><AtSign className="size-3" />route</span></p>
          </form>
        </div>
      </div>
    </div>
  );
}
