"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, GitBranch, Lightning } from "@phosphor-icons/react";

const EASE = [0.25, 1, 0.5, 1] as const;

export default function EngineeringProof() {
  return (
    <section className="relative conduit-section conduit-bg-canvas border-t border-[var(--color-edge-subtle)] overflow-hidden">
      {/* Subtle ember radial */}
      <div
        aria-hidden
        className="absolute -top-40 -left-40 w-[700px] h-[700px] pointer-events-none"
        style={{
          background:
            "radial-gradient(ellipse at center, rgba(91, 99, 232,0.08) 0%, transparent 60%)",
        }}
      />

      <div className="relative conduit-container">
        <div className="grid lg:grid-cols-[minmax(0,420px)_minmax(0,1fr)] gap-12 lg:gap-16">
          {/* Left — header */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-15%" }}
            transition={{ duration: 0.8, ease: EASE }}
            className="lg:sticky lg:top-32 lg:self-start"
          >
            <p className="conduit-caption conduit-caption-ember">
              Praxis Engineering · Live
            </p>
            <h2 className="conduit-display-xl mt-5">
              Real workforces ship.{" "}
              <span className="conduit-ember-text">Not summaries.</span>
            </h2>
            <p className="conduit-body-lg mt-6">
              Praxis Engineering takes a one-line ask, opens a sandbox, writes
              the code, runs the build, and pushes the deploy. The output is
              production code, not a plan.
            </p>

            <div className="mt-8 grid grid-cols-2 gap-4">
              <Stat
                Icon={Lightning}
                n="7m"
                label="Build to deploy"
              />
              <Stat
                Icon={GitBranch}
                n="100%"
                label="Real commits"
              />
            </div>

            <Link
              href="/auth/sign-up"
              className="conduit-btn-primary mt-10"
            >
              Run a build
              <ArrowRight size={16} weight="bold" />
            </Link>
          </motion.div>

          {/* Right — code preview */}
          <motion.div
            initial={{ opacity: 0, scale: 0.97 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true, margin: "-10%" }}
            transition={{ duration: 1.0, ease: EASE }}
          >
            <CodeBlock />
            <p className="conduit-caption conduit-caption-ember mt-6">
              This is real. Generated by Praxis Engineering today.
            </p>
            <p className="text-[13px] text-[var(--color-cream-mute)] mt-2 leading-[1.6] max-w-[600px]">
              Snippet from the Lunaro Insurance pipeline build that shipped at
              09:42 this morning. Full session log in /app/builds.
            </p>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

function Stat({
  Icon,
  n,
  label,
}: {
  Icon: typeof Lightning;
  n: string;
  label: string;
}) {
  return (
    <div className="conduit-card p-4">
      <Icon size={18} weight="regular" color="#5B63E8" />
      <span
        className="block text-[26px] leading-[1.0] text-[var(--color-cream)] tracking-[-0.025em] mt-3"
        style={{ fontFamily: "var(--font-serif)", fontWeight: 500 }}
      >
        {n}
      </span>
      <span className="text-[11px] uppercase tracking-[0.08em] text-[var(--color-cream-mute)] mt-1 block">
        {label}
      </span>
    </div>
  );
}

function CodeBlock() {
  return (
    <div className="conduit-code-frame">
      <div className="conduit-code-inner">
        {/* Tab bar */}
        <div className="flex items-center gap-3 mb-5 -mt-1 -mx-1">
          <div className="flex gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-[#FF6058]/60" />
            <span className="w-2.5 h-2.5 rounded-full bg-[#FFBD2E]/60" />
            <span className="w-2.5 h-2.5 rounded-full bg-[#28C940]/60" />
          </div>
          <span className="text-[11px] text-[var(--color-cream-mute)]">
            src/app/dashboard/pipeline/page.tsx
          </span>
          <span className="ml-auto inline-flex items-center gap-1.5 text-[10px] uppercase tracking-wider text-[var(--color-conduit-success)]">
            <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-conduit-success)] shadow-[0_0_6px_currentColor]" />
            Deployed
          </span>
        </div>

        {/* Code lines */}
        <div className="text-[13px] leading-[1.7] tracking-[-0.005em] whitespace-pre">
          <Line>
            <C>{"// Generated by Praxis Engineering · 2026-05-08T09:42:18Z"}</C>
          </Line>
          <Line>
            <K>{"import"}</K>
            {" { "}
            <V>{"createClient"}</V>
            {" } "}
            <K>{"from"}</K>{" "}
            <S>{`"@/lib/supabase/server"`}</S>;
          </Line>
          <Line>
            <K>{"import"}</K>
            {" { "}
            <V>{"PipelineBoard"}</V>
            {" } "}
            <K>{"from"}</K>{" "}
            <S>{`"@/components/PipelineBoard"`}</S>;
          </Line>
          <Line />
          <Line>
            <K>{"export default async function"}</K>{" "}
            <F>{"PipelinePage"}</F>
            {"() {"}
          </Line>
          <Line indent={1}>
            <K>{"const"}</K>{" "}
            <V>{"supabase"}</V>
            {" = "}
            <K>{"await"}</K>{" "}
            <F>{"createClient"}</F>
            {"();"}
          </Line>
          <Line indent={1}>
            <K>{"const"}</K>
            {" { "}
            <V>{"data"}</V>
            {": "}
            <V>{"stages"}</V>
            {" } = "}
            <K>{"await"}</K>{" "}
            <V>{"supabase"}</V>
          </Line>
          <Line indent={2}>
            .<F>{"from"}</F>
            {"("}
            <S>{`"pipeline_stages"`}</S>
            {")"}
          </Line>
          <Line indent={2}>
            .<F>{"select"}</F>
            {"("}
            <S>{`"id, name, position, deals(*)"`}</S>
            {")"}
          </Line>
          <Line indent={2}>
            .<F>{"order"}</F>
            {"("}
            <S>{`"position"`}</S>
            {");"}
          </Line>
          <Line />
          <Line indent={1}>
            <K>{"return"}</K>
            {" ("}
          </Line>
          <Line indent={2}>
            {"<"}
            <T>{"main"}</T>{" "}
            <V>{"className"}</V>
            {"="}
            <S>{`"min-h-screen bg-canvas"`}</S>
            {">"}
          </Line>
          <Line indent={3}>
            {"<"}
            <T>{"PipelineBoard"}</T>{" "}
            <V>{"stages"}</V>
            {"={stages ?? []} />"}
          </Line>
          <Line indent={2}>
            {"</"}
            <T>{"main"}</T>
            {">"}
          </Line>
          <Line indent={1}>{"  );"}</Line>
          <Line>{"}"}</Line>
        </div>
      </div>
    </div>
  );
}

function Line({
  children,
  indent = 0,
}: {
  children?: React.ReactNode;
  indent?: number;
}) {
  return (
    <div style={{ paddingLeft: `${indent * 16}px`, minHeight: "1lh" }}>
      {children}
    </div>
  );
}

// Token color spans
function K({ children }: { children: React.ReactNode }) {
  return <span style={{ color: "#A8AFFB" }}>{children}</span>;
}
function V({ children }: { children: React.ReactNode }) {
  return <span style={{ color: "#F5EFE6" }}>{children}</span>;
}
function S({ children }: { children: React.ReactNode }) {
  return <span style={{ color: "#9DD8B1" }}>{children}</span>;
}
function F({ children }: { children: React.ReactNode }) {
  return <span style={{ color: "#FFC899" }}>{children}</span>;
}
function T({ children }: { children: React.ReactNode }) {
  return <span style={{ color: "#5B63E8" }}>{children}</span>;
}
function C({ children }: { children: React.ReactNode }) {
  return <span style={{ color: "#847A6E", fontStyle: "italic" }}>{children}</span>;
}
