-- Create a private Supabase Storage bucket for chat audio messages.
-- Audio files are stored as: {user_id}/{uuid}.webm
-- Max file size 5 MB (5 242 880 bytes), audio MIME types only.
-- All access is via short-lived signed URLs (1 hour TTL) generated by the client SDK.
-- RLS ensures each user can only read/write/delete their own files.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'chat-audio',
  'chat-audio',
  false,
  5242880,
  ARRAY[
    'audio/webm',
    'audio/webm;codecs=opus',
    'audio/ogg',
    'audio/ogg;codecs=opus',
    'audio/mp4',
    'audio/mpeg',
    'audio/wav'
  ]
) ON CONFLICT (id) DO NOTHING;

-- Users can upload to their own subfolder only ({user_id}/...)
CREATE POLICY "chat_audio_insert"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'chat-audio'
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Users can read their own audio files only
CREATE POLICY "chat_audio_select"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'chat-audio'
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Users can delete their own audio files
CREATE POLICY "chat_audio_delete"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'chat-audio'
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
